name: ssvm_environment
channels:
  - conda-forge
  - bioconda
dependencies:
  - python
  - numpy
  - scikit-learn
  - pandas
  - scipy
  - joblib
  - pip
  - matchms
  - more-itertools
  - tqdm
  - tensorflow>=2.0
  - tbb
  - numba
  - opt_einsum