name: lcms2struct
channels:
  - conda-forge
  - default
dependencies:
  - conda-forge::python>=3.8|<3.10
  - conda-forge::pandas==1.2.4
  - conda-forge::numpy==1.20.2
  - conda-forge::scikit-learn<1
  - conda-forge::scipy==1.6.2
  - conda-forge::joblib==1.0.1
  - bioconda::matchms==0.9.2
  - conda-forge::more-itertools
  - conda-forge::tqdm
  - conda-forge::tbb
  - conda-forge::numba==0.53.1
  - conda-forge::networkx>=2.4|<3
