name: Unit-testing

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8' ]

    defaults:
      run:
        # Set up the default shell. This is needed for the Conda
        shell: bash -l {0}

    steps:
      # ------------------------------------------------------------------------
      # Checkout the branch from the github repository that triggered the action
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      # ------------------------------------------------------------------------

      # --------------------------------------------------
      # Setting up Python using a Conda environment
      - name: Set up Conda with Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ssvm_environment
          environment-file: environment.yml
          channel-priority: strict
      # --------------------------------------------------

      # ------------------------
      # Install the SSVM package
      - name: Install the SSVM package
        run: pip install .
      # ------------------------

      # --------------------------------
      # Check the package version number
      - name: Package version number
        run: python -c "from ssvm import __version__; print('SSVM-Package version:', __version__)"
      # --------------------------------

      # ------------------------
      # Decompress the test data
      - name: Gun-zipping the test SQLite DB
        run: |
          gunzip ssvm/tests/Bach2020_test_db.sqlite.gz
          gunzip ssvm/tests/Massbank_test_db.sqlite.gz
      # ------------------------

      # -----------------
      # Run the unittests
      - name: Run all unittests
        run: |
          cd ssvm/tests
          python -m unittest -v unittests_data_structures.py
          python -m unittest -v unittests_dual_variables.py
          python -m unittest -v unittests_evaluation_tools.py
          python -m unittest -v unittests_kernel_utils.py
          python -m unittest -v unittests_loss_functions.py
          python -m unittest -v unittests_utils.py
          python -m unittest -v unittests_feature_utils.py
          python -m unittest -v unittests_ssvm.py
      # -----------------
